version: '3.9'

services:
  WEB_1:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - /home/ubuntu/index_html/index1.html:/usr/share/nginx/html/index.html
    
  WEB_2:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - /home/ubuntu/index_html/index2.html:/usr/share/nginx/html/index.html
  
  WEB_3:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - /home/ubuntu/index_html/index3.html:/usr/share/nginx/html/index.html
 