version: '3.9'

services:
  reverse_proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - WEB_1
      - WEB_2
      - WEB_3
    networks:
      - proxy_net

  WEB_1:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - /home/ubuntu/index_html/Task_2/index1.html:/usr/share/nginx/html/index.html
    
  WEB_2:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - /home/ubuntu/index_html/Task_2/index2.html:/usr/share/nginx/html/index.html
  
  WEB_3:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - /home/ubuntu/index_html/Task_2/index3.html:/usr/share/nginx/html/index.html

networks:
  proxy_net:
    driver: bridge
 